# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Shunyi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


pod 'MJRefresh'
pod 'AFNetworking','4.0.1'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'Masonry'
pod 'SDWebImage'
pod 'MJExtension', '3.2.2'
pod 'Toast'
pod 'ReactiveObjC'
pod 'IQKeyboardManager'
pod 'Realm'
pod 'Bugly','2.5.0'

end
